id: PA04D8B86
initial_creation_type: input
source_metadata:
  title: Doxographical works
  parent: 3. Various collections
  source: https://sakyalibrary.com
  bases:
    abde:
      title: སྡེ་དགེ་རྒྱལ་པོས་མཛད་པའི་གྲུབ་མཐའི་སྡོམ་ཚིག་བཞུགས།
      author: སྡེ་དགེ་རྒྱལ་པོ།
      base_file: abde.txt
      order: 1
    7c1b:
      title: གྲུབ་མཐའ་ཀུན་ཤེས་ནས་མཐའ་བྲལ་གྲུབ་པ་ཞེས་བྱ་བའི་བསྟན་བཅོས་དང་། དེའི་རྣམ་པར་བཤད་པ་ལེགས་བཤད་ཀྱི་རྒྱ་མཚོ།
      author: སྟག་ཚང་ལོ་ཙཱ་བ་ཤེས་རབ་རིན་ཆེན།
      base_file: 7c1b.txt
      order: 2
created_at: '2022-04-06T18:05:31.297376'
last_modified_at: '2022-04-06T18:05:31.297385'
